model: "text_image_resnet_dialogue_summarization_model" # The exact filename that the model is stored in, excluding the .py extension
modality: "text-image-dialogue" # "text" | "image" | "text-image" | "text-image-dialogue"
num_classes: 3 # 2 | 3 | 6
batch_size: 64 # (int) Increase this as much as you can to maximize GPU utilization without exceeding CUDA memory
learning_rate: 1.0e-4 # (float) Note that the mantissa must have a decimal point to be parsed by YAML as a float (and not a str)
num_epochs: 2 # (int)
dropout_p: 0.1 # (float)
fusion_output_size: 512 # (int) Dimension after multi-modal embeddings fusion
gpus: [0, 1] # [0] | [1] | [0, 1] Note that it must be a list of ints
num_cpus: 0 # 0 for no multi-processing (during dataset batching), 24 for Yale Tangra server, 40 for Yale Ziva server
text_embedder: "all-distilroberta-v1" # "all-mpnet-base-v2" | "all-distilroberta-v1"
image_encoder: "resnet" # "resnet" | "dino"
dialogue_summarization_model: "sshleifer/distilbart-cnn-12-6" # None=Transformers.Pipeline default i.e. "sshleifer/distilbart-cnn-12-6" | "bart-large-cnn" | "t5-small" | "t5-base" | "t5-large"
train_data_path: "./data/Fakeddit/multimodal_train_10000.tsv" # (str)
test_data_path: "./data/Fakeddit/multimodal_test_1000.tsv" # (str)
preprocessed_train_dataframe_path: "./data/Fakeddit/train__text_image_dialogue__dataframe.pkl" # (str)
preprocessed_test_dataframe_path: "./data/Fakeddit/test__text_image_dialogue__dataframe.pkl" # (str)
trained_model_version: 1 # 16 for 5 epochs # (int)
trained_model_path: null # (str) Not needed if you specify trained_model_version and it's in lightning_logs/
